[versions]
agp = "8.10.0"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.4"
google-service = "4.4.4"

compose-bom = "2025.08.00"
core-ktx = "1.17.0"
activity-compose = "1.11.0"
lifecycle = "2.9.4"
navigation = "2.9.4"

coroutines = "1.10.2"
room = "2.8.1"
dagger = "2.57.2"
lottie = "6.7.1"
firebase-bom = "34.6.0"
junit = "4.13.2"
junit-version = "1.3.0"
espresso-core = "3.7.0"
amazon = "2.81.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }

amazon-s3 = { module = "com.amazonaws:aws-android-sdk-s3", version.ref = "amazon"}

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[bundles]
compose-base = [
    "androidx-core-ktx",
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-runtime-compose",
    "compose-ui",
    "compose-foundation",
    "compose-material3",
    "compose-ui-tooling-preview",
]

coroutines = [
    "coroutines-core",
    "coroutines-android",
]

room = [
    "room-runtime",
    "room-ktx",
]

firebase = [
    "firebase-auth",
    "firebase-firestore",
    "firebase-storage",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
firebase = { id = "com.google.gms.google-services", version.ref = "google-service"}